version: "3.2"
services:

    mysql:
      image: mysql:5.7
      container_name: mysql_1
      working_dir: /src
      volumes:
        - ${PHP_CODE}:/src
        - ${MYSQL_DATA}:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=dev_admin
        - MYSQL_DATABASE=products
        - MYSQL_USER=devdb_dev
        - MYSQL_PASSWORD=devdb1234
      command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_general_ci']
      ports:
        - "1027:3306"

    php:
      build:
        context: ./docker/php-apache/
      environment:
        XDEBUG_CONFIG: remote_host=${HOST_IP}
        XDEBUG_IDE_KEY: ${XDEBUG_IDE_KEY}
      container_name: php_1
      working_dir: /src
      volumes:
        - ${PHP_CODE}:/src
        - ./docker/php-apache/php-ini-overrides.ini:/usr/local/etc/php/conf.d/php-ini-overrides.ini
      ports:
        - "1028:80"
