version: "3.2"
services:

    mysql:
      image: mysql:5.7
      container_name: mysql-5.7-dev
      working_dir: /src
      volumes:
        - ./src:/src
      environment:
        - MYSQL_ROOT_PASSWORD=dev_admin
        - MYSQL_DATABASE=devdb
        - MYSQL_USER=devdb_dev
        - MYSQL_PASSWORD=devdb1234
      command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
      ports:
        - "1027:3306"

    php:
      build:
        context: ./docker/php-apache/
      environment:
        XDEBUG_CONFIG: remote_host=$IDE_HOST
      container_name: php5.6-apache-dev
      working_dir: /src
      volumes:
        - ./src:/src
        - ./docker/php-apache/php-ini-overrides.ini:/usr/local/etc/php/conf.d/docker-php-pecl-xdebug.ini
      ports:
        - "1028:80"
